api:
  dashboard: true
experimental:
  plugins:
    crowdsec-bouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.7.1"
log:
  level: INFO
  format: common

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    proxyProtocol:
      trustedIPs:
        - "10.100.0.1/32"
    http:
      tls:
        certResolver: "letsencrypt"
        domains:
          - main: "daberga.com"
            sans:
              - "*.daberga.com"
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "192.168.10.140/32"
        - "10.100.0.1/32"
        
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "bergatrix-proxy"
  file:
    directory: "/tmp/traefik-dynamic"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: "/acme.json"
      dnsChallenge:
        provider: desec
        resolvers:
          - "ns1.desec.io:53"
          - "ns2.desec.org:53"
        propagation:
          delayBeforeChecks: 60s
