log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: "letsencrypt"
        domains:
          - main: "bergaestudio.xyz"
            sans:
              - "*.bergaestudio.xyz"
    # Configuração refinada: o Traefik agora confia apenas no seu gateway
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"       # Localhost
        - "192.168.10.0/24"    # A rede interna (que já inclui o .1 do OPNsense)
        - "100.64.0.0/10"      # A rede virtual da Tailscale
        - "10.8.0.0/24"        # A rede do WireGuard (Verifique qual é a sub-rede do seu túnel com a Oracle e coloque aqui)
        - "192.168.3.0/24"     # Rede local backup
        - "fd6d:f154:e57d::/64" #Rede ipv6
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "bergatrix-proxy"

certificatesResolvers:
  letsencrypt:
    acme:
      storage: "/acme.json"
      dnsChallenge:
        provider: desec
        propagation:
          delayBeforeChecks: "30s"
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
