services:
  traefik:
    image: traefik:v3.6.2
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - "/bin/sh"
      - "/start-traefik.sh"
    networks:
      - bergatrix-proxy
    ports:
      - 80:80
      - 443:443
    dns:
      - 9.9.9.9
      - 149.112.112.112
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/traefik.yml:ro
      - ./config/dynamic.yml:/config-source/dynamic.yml:ro
      - ./config/config.yml:/config-source/config.yml:ro
      - ./config/acme.json:/acme.json
      - ./config/start-traefik.sh:/start-traefik.sh:ro
      - ${STORAGE_PATH}/traefik/logs:/var/log/traefik
    environment:
      - DESEC_TOKEN=${DESEC_TOKEN}
      - DESEC_DOMAIN=${DOMAIN}
      - SUBDOMAIN_TRAEFIK_DASHBOARD=${SUBDOMAIN_TRAEFIK_DASHBOARD}
      - TRAEFIK_USER=${TRAEFIK_USER}
      - TRAEFIK_PASSWORD=${TRAEFIK_PASSWORD}
      - CROWDSEC_BOUNCER_KEY=${CROWDSEC_BOUNCER_KEY}
      - LEGO_DISABLE_CNAME_SUPPORT=true
    labels:
      - "traefik.enable=true"

networks:
  bergatrix-proxy:
    name: bergatrix-proxy
    external: true
