services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    restart: unless-stopped
    volumes:
      - ${STORAGE_PATH}/vaultwarden:/data
    networks:
      - bergatrix-proxy
    environment:
      - SIGNUPS_ALLOWED=false
      - TZ=America/Sao_Paulo
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - DOMAIN=https://bitwarden.${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=bergatrix-proxy"
      
      - "traefik.http.routers.vaultwarden-router.rule=Host(`bitwarden.${DOMAIN}`) && !PathPrefix(`/api-access-bypass`) && !(ClientIP(`192.168.10.140/32`) || ClientIP(`192.168.10.121/32`) || ClientIP(`192.168.10.1/32`))"
      - "traefik.http.routers.vaultwarden-router.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-router.tls=true"
      - "traefik.http.routers.vaultwarden-router.service=vaultwarden-service"
      - "traefik.http.routers.vaultwarden-router.middlewares=crowdsec-bouncer@file,public-auth@file"
      - "traefik.http.routers.vaultwarden-router.priority=100"

      - "traefik.http.routers.vaultwarden-direct.rule=Host(`bitwarden.${DOMAIN}`) && (ClientIP(`192.168.10.140/32`) || ClientIP(`192.168.10.121/32`) || ClientIP(`192.168.10.1/32`))"
      - "traefik.http.routers.vaultwarden-direct.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-direct.tls=true"
      - "traefik.http.routers.vaultwarden-direct.service=vaultwarden-service"
      - "traefik.http.routers.vaultwarden-direct.priority=110"

      - "traefik.http.routers.vaultwarden-bypass.rule=Host(`bitwarden.${DOMAIN}`) && PathPrefix(`/api-access-bypass`)"
      - "traefik.http.routers.vaultwarden-bypass.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-bypass.tls=true"
      - "traefik.http.routers.vaultwarden-bypass.service=vaultwarden-service"
      - "traefik.http.routers.vaultwarden-bypass.middlewares=crowdsec-bouncer@file,api-access-bypass@file"
      - "traefik.http.routers.vaultwarden-bypass.priority=120"

      - "traefik.http.routers.vaultwarden-ws-router.rule=Host(`bitwarden.${DOMAIN}`) && PathPrefix(`/notifications/hub`) && !(ClientIP(`192.168.10.140/32`) || ClientIP(`192.168.10.121/32`) || ClientIP(`192.168.10.1/32`))"
      - "traefik.http.routers.vaultwarden-ws-router.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-ws-router.tls=true"
      - "traefik.http.routers.vaultwarden-ws-router.service=vaultwarden-ws-service"
      - "traefik.http.routers.vaultwarden-ws-router.middlewares=crowdsec-bouncer@file,public-auth@file"
      - "traefik.http.routers.vaultwarden-ws-router.priority=105"

      - "traefik.http.routers.vaultwarden-ws-direct.rule=Host(`bitwarden.${DOMAIN}`) && PathPrefix(`/notifications/hub`) && (ClientIP(`192.168.10.140/32`) || ClientIP(`192.168.10.121/32`) || ClientIP(`192.168.10.1/32`))"
      - "traefik.http.routers.vaultwarden-ws-direct.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-ws-direct.tls=true"
      - "traefik.http.routers.vaultwarden-ws-direct.service=vaultwarden-ws-service"
      - "traefik.http.routers.vaultwarden-ws-direct.priority=115"

      - "traefik.http.routers.vaultwarden-ws-bypass.rule=Host(`bitwarden.${DOMAIN}`) && PathPrefix(`/api-access-bypass/notifications/hub`)"
      - "traefik.http.routers.vaultwarden-ws-bypass.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-ws-bypass.tls=true"
      - "traefik.http.routers.vaultwarden-ws-bypass.service=vaultwarden-ws-service"
      - "traefik.http.routers.vaultwarden-ws-bypass.middlewares=crowdsec-bouncer@file,api-access-bypass@file"
      - "traefik.http.routers.vaultwarden-ws-bypass.priority=125"

      # --- Definição de Serviços ---
      - "traefik.http.services.vaultwarden-service.loadbalancer.server.port=80"
      - "traefik.http.services.vaultwarden-ws-service.loadbalancer.server.port=3012"

networks:
  bergatrix-proxy:
    name: bergatrix-proxy
    external: true
