services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    volumes:
      - ${STORAGE_PATH}/cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      - bergatrix-proxy       # Para o Traefik levar o tráfego
      - bergatrix-db-internal # Para ele alcançar o Postgres Global
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=bergatrix-proxy"
      - "traefik.http.routers.cloudbeaver.rule=Host(`db.${DOMAIN}`) && !PathPrefix(`/api-access-bypass`) && !(ClientIP(`192.168.10.140/32`) || ClientIP(`192.168.10.121/32`) || ClientIP(`192.168.10.1/32`))"
      - "traefik.http.routers.cloudbeaver.entrypoints=websecure"
      - "traefik.http.routers.cloudbeaver.tls=true"
      - "traefik.http.routers.cloudbeaver.service=cloudbeaver-service"
      - "traefik.http.routers.cloudbeaver.middlewares=crowdsec-bouncer@file,public-auth@file"
      - "traefik.http.routers.cloudbeaver.priority=100"
      - "traefik.http.routers.cloudbeaver-direct.rule=Host(`db.${DOMAIN}`) && (ClientIP(`192.168.10.140/32`) || ClientIP(`192.168.10.121/32`) || ClientIP(`192.168.10.1/32`))"
      - "traefik.http.routers.cloudbeaver-direct.entrypoints=websecure"
      - "traefik.http.routers.cloudbeaver-direct.tls=true"
      - "traefik.http.routers.cloudbeaver-direct.service=cloudbeaver-service"
      - "traefik.http.routers.cloudbeaver-direct.priority=110"
      - "traefik.http.routers.cloudbeaver-bypass.rule=Host(`db.${DOMAIN}`) && PathPrefix(`/api-access-bypass`)"
      - "traefik.http.routers.cloudbeaver-bypass.entrypoints=websecure"
      - "traefik.http.routers.cloudbeaver-bypass.tls=true"
      - "traefik.http.routers.cloudbeaver-bypass.service=cloudbeaver-service"
      - "traefik.http.routers.cloudbeaver-bypass.middlewares=crowdsec-bouncer@file,api-access-bypass@file"
      - "traefik.http.routers.cloudbeaver-bypass.priority=120"
      - "traefik.http.services.cloudbeaver-service.loadbalancer.server.port=8978"

networks:
  bergatrix-proxy:
    external: true
  bergatrix-db-internal:
    external: true
