services:
  postgres-global:
    image: postgres:16-alpine
    container_name: postgres-global
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${STORAGE_PATH}/postgres-global/data:/var/lib/postgresql/data
    networks:
      - bergatrix-db-internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  bergatrix-db-internal:
    name: bergatrix-db-internal
    driver: bridge