services:
  wireguard-connector:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-connector
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${STORAGE_PATH}/wg-connector/config/wg0.conf:/config/wg0.conf
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - bergatrix-proxy

networks:
  bergatrix-proxy:
    name: bergatrix-proxy
    external: true