name: bergastream
description: Bergastream, app de streaming musical self-hosted.
publish_to: none
version: 0.1.5+105

environment:
  sdk: ^3.12.0

# Os pacotes da Seção 3 da Documentação entram no passo que os usa.
dependencies:
  audio_service: ^0.18.19
  audio_session: ^0.2.4
  background_downloader: ^9.5.9
  connectivity_plus: ^7.3.2
  dio: ^5.11.1
  drift: ^2.35.1
  drift_flutter: ^0.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  flutter_secure_storage: ^11.2.0
  go_router: ^18.0.2
  image_picker: ^1.2.4
  json_annotation: ^4.12.0
  just_audio: ^0.10.6
  just_audio_media_kit: ^2.1.0
  media_kit_libs_linux: ^1.2.1
  media_kit_libs_windows_audio: ^1.0.9
  open_filex: ^4.7.0
  package_info_plus: ^10.2.2
  path_provider: ^2.1.6
  share_plus: ^13.3.1
  url_launcher: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.14.1
  build_runner: ^2.15.1
  drift_dev: ^2.35.1

flutter:
  uses-material-design: true
  fonts:
    - family: BricolageGrotesque
      fonts:
        - asset: assets/fonts/BricolageGrotesque-Regular.ttf
          weight: 400
        - asset: assets/fonts/BricolageGrotesque-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BricolageGrotesque-ExtraBold.ttf
          weight: 800
