services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard-router.rule=Host(`dns.${DOMAIN}`)"
      - "traefik.http.routers.adguard-router.entrypoints=websecure"
      - "traefik.http.routers.adguard-router.tls=true"
      - "traefik.http.routers.adguard-router.tls.certresolver=letsencrypt"
      - "traefik.http.routers.adguard-router.middlewares=internal-only@docker"
      - "traefik.http.services.adguard-service.loadbalancer.server.url=http://192.168.10.112:3000"
